Vagrant.configure("2") do |config|
  config.vm.define "test-ssh-vm" do |test|
    test.vm.box = "ubuntu/focal64"
    test.vm.hostname = "test-ssh-vm"
    test.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: false
    test.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # Reduz a RAM para 1GB
      vb.cpus = 1        # 1 CPU
      vb.gui = true      # Mostrar a interface gráfica da VM
    end
  end
end