version: '3.8'

services:
  express_service_1:
    build: ./express-service-1
    environment:
      - SERVICE_NAME=Express Service 1
    # Não vamos expor a porta 3001 da VM para o host para simplificar,
    # já que o Nginx vai encaminhar o tráfego internamente.
    # ports:
    #   - "3001:3000"
    deploy:
      replicas: 3 # Múltiplas instâncias para balanceamento de carga interno do Docker
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  nginx_gateway:
    build: ./nginx
    ports:
      - "80:80" # Mapeia a porta 80 da VM para a porta 80 do host (agora a única VM)
    depends_on:
      - express_service_1 # Agora depende apenas do Express Service 1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge