---
- name: Setup Docker and deploy application with Docker Compose
  hosts: all # Aplica a todas as VMs definidas no inventory
  become: yes # Executa as tarefas com sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install apt-transport-https and ca-certificates
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin # Para o novo 'docker compose' (plugin)

    - name: Add 'vagrant' user to the docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Create app directory on VMs
      file:
        path: /home/vagrant/app
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy application files to VMs
      copy:
        src: files/ # Copia o conteúdo da pasta 'files'
        dest: /home/vagrant/app/
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Ensure docker-compose.yml has correct permissions
      file:
        path: /home/vagrant/app/docker-compose.yml
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Start Docker Compose application
      command: docker compose up -d
      args:
        chdir: /home/vagrant/app
      become: no # Executa como o usuário 'vagrant', não como root
      register: docker_compose_output

    - name: Display docker compose output
      debug:
        var: docker_compose_output.stdout_lines